import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CountryProvider } from "./context/CountryContext";
import { ThemeProvider } from "./context/ThemeContext";
import { THEME_STORAGE_KEY } from "./lib/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Worldwide Pride Index",
  description: "Generated by Gal Ishlach",
};

// Runs before first paint so the saved (or system) theme is on <html> before
// the page is visible. Mirrors the resolution in ThemeContext.
const themeInitScript = `(function(){var c=null;try{c=localStorage.getItem("${THEME_STORAGE_KEY}")}catch(e){}var d=c==="dark"||(c!=="light"&&window.matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=d?"dark":"light"})();`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <CountryProvider>
          {children}
          </CountryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
